CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ip_blacklist (
    id SERIAL PRIMARY KEY,
    ip_address VARCHAR(45) UNIQUE NOT NULL,
    failed_attempts INTEGER DEFAULT 1,
    blocked_until TIMESTAMP,
    last_attempt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===== Assignment 4: Data Protection & Automated Security Tables =====

-- Encrypted file storage across distributed nodes
CREATE TABLE IF NOT EXISTS encrypted_files (
    id SERIAL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    owner_username VARCHAR(50) NOT NULL,
    encrypted_content BYTEA NOT NULL,
    encryption_key_id VARCHAR(100) NOT NULL,
    storage_node VARCHAR(50) NOT NULL,
    file_size_bytes INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Encryption key metadata (wrapped DEKs stored here)
CREATE TABLE IF NOT EXISTS encryption_keys (
    id SERIAL PRIMARY KEY,
    key_id VARCHAR(100) UNIQUE NOT NULL,
    key_purpose VARCHAR(50) NOT NULL DEFAULT 'data',
    wrapped_key TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rotated_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    node_id VARCHAR(50)
);

-- Access logs for anomaly detection
CREATE TABLE IF NOT EXISTS access_logs (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50),
    ip_address VARCHAR(45),
    endpoint VARCHAR(255),
    method VARCHAR(10),
    status_code INTEGER,
    storage_node VARCHAR(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Security alerts generated by anomaly detection
CREATE TABLE IF NOT EXISTS security_alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    description TEXT NOT NULL,
    source_ip VARCHAR(45),
    username VARCHAR(50),
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User access restrictions (node/file level blocking)
CREATE TABLE IF NOT EXISTS access_restrictions (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    restriction_type VARCHAR(50) NOT NULL,
    target VARCHAR(255),
    reason TEXT,
    restricted_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Refresh token tracking for token renewal
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id SERIAL PRIMARY KEY,
    token_hash VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===== Distributed Synchronization Tables =====

-- Tracks sync events for cross-node replication
CREATE TABLE IF NOT EXISTS sync_events (
    id SERIAL PRIMARY KEY,
    event_id VARCHAR(100) UNIQUE NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    source_node VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    applied BOOLEAN DEFAULT TRUE
);

-- Retry queue for failed sync pushes
CREATE TABLE IF NOT EXISTS sync_retry_queue (
    id SERIAL PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    target_node VARCHAR(255) NOT NULL,
    retry_count INTEGER DEFAULT 0,
    last_attempt TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
